### PR TITLE
Made JSON validator only actually check files in the NetKAN directory

### PR DESCRIPTION
**Pull request by Rohaq**

### CODE REVIEW

**Comment by Rohaq** [comment]
I noticed that there's no skipping in \CKAN-meta\build.sh either, does this need to be added there, too?

**Comment by HebaruSan** [comment]
The [CKAN-meta repo](https://github.com/KSP-CKAN/CKAN-meta) has no NetKAN folder, so no, I wouldn't apply this change to that script.

Can you also update the `$ckan` variable name in the error message?

**Comment by Rohaq** [comment]
Good spot, done!

**Comment by HebaruSan** [comment]
LGTM, but I think this repo requires some manual steps by @techman83 post-merge to update the server where this code runs, so I'll leave this open till he can take a look at it. Thanks for the fix!

**Comment by Rohaq** [comment]
No worries, once it's confirmed as up and running, I'll put in a PR to get that one Perl file fixed up too :)

**Comment by techman83** [comment]
LGTM too. Thanks for your efforts @Rohaq  and thanks for reviewing @HebaruSan! These files get picked up by the testing infrastructure automatically :)

**Pull request merged**
