### PR TITLE
Display path of located 'GameData' directories for easier diagnosis

### PR DESCRIPTION
**Pull request by techman83**
@politas  this will address the difficulty of diagnosing #4491

### CODE REVIEW

**Comment by politas** [comment]
Can we still rebuild, or will that no longer work? Merging for future issues at least.

**Comment by techman83** [comment]
You can rebuild from Jenkins, not sure if you can rebuild using `#rebuild` on merged PRs.

**Comment by politas** [comment]
I tried rebuilding from Jenkins, but it gave the same lack of data. I guess it still has the old build.sh in that branch.

**Comment by techman83** [comment]
Nah, it pulls from the xKan-meta-testing everytime. The example I pulled was from rerunning @linuxgurugamer's build. What's the build number?

**Comment by politas** [comment]
The same one. I guess it was still showing me the old results.

**Comment by techman83** [comment]
Nope, though you have to look at the actual build.

https://ci.ksp-ckan.org/job/NetKAN/4143/console

**Pull request merged**
