### PR TITLE
Handle multiple ckans per netkan

### LINKED ISSUE #69: [Feature] Diff and install multiple ckans per netkan
## Background

KSP-CKAN/CKAN#3279 made it possible to inflate multiple ckan files for one netkan with multi-asset releases on GitHub.

## Problem

Currently the PR validation code assumes only one ckan will be inflated per netkan.

For example, see KSP-CKAN/NetKAN#8353; Kopernicus currently inflates 4 ckans for its latest release, but only 1 of them was diffed and installed.

## Causes

Right now the user or calling code has no way to know directly what `netkan.exe` just did after it finishes running, other than checking its exit code for an error. If it finished successfully, it will have created one or more ckans somewhere in its output folder.

Currently the validation action passes a shared output folder to `netkan.exe` and then assumes that the most recently created file is the ckan for it, which obviously won't handle multiple ckans.

https://github.com/KSP-CKAN/xKAN-meta_testing/blob/0dd3e751abce86cb02036407f5a99c4880ca069d/ckan_meta_tester/ckan_meta_tester.py#L113-L117

## Suggestions

Maybe we could inflate each netkan into a fresh temp folder, scan it for ckan files, and then copy them to the `self.INFLATED_PATH` folder? That way we could track which ckans are for which netkans and not miss installing them.

### PR DESCRIPTION
**Pull request by HebaruSan**
Fixes #69; the problem and solution are described in that issue.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Based on running analogous code, apparently this is happening silently now :snake:

```
ValueError: too many values to unpack (expected 2)
```

**Comment by HebaruSan** [comment]
Now it prints them all but doesn't diff or inflate anything. :frowning_face:

**Comment by HebaruSan** [comment]
`Path.rglob` returns a generator, which only works once; the `for` loop exhausts it, so it's empy when we use it again.

:snake:

**Comment by techman83** [comment]
Well a generator is supposed to be like that, you can cast it to a list if you want list like behaviour. For our use case here (a very small amount of files), it's probably appropriate. Generators have their use case, especially if memory constrained.

**Comment by techman83** [comment]
I've not had enough time to fully familiarise myself with this code just yet, do we have much test coverage?

I'm doing this to get a full list of file changes in one of my projects:


```yaml
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Build changes
        run: |
          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }})
```

**Comment by HebaruSan** [comment]
Yes, the tests pretty much cover everything except the new functionality in this PR:

https://github.com/KSP-CKAN/xKAN-meta_testing/tree/master/tests

**Pull request merged**
